version: '3.4'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: blog-platform
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/blog
    depends_on:
      - mongo

volumes:
  mongo-data: